version: 43.0.9
pageUuid: 8f995b94-cc78-11eb-9c5e-8fecb3528ed0
appTemplate:
  tests:
    array: []
  urlFragmentDefinitions: []
  appStyles: ''
  appThemeId: null
  preloadedAppJavaScript: null
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  testEntities:
    array: []
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  preloadedAppJSLinks:
    array: []
  version: 2.71.0
  responsiveLayoutDisabled: false
  createdAt: null
  customShortcuts:
    array: []
  loadingIndicatorsDisabled: false
